# Generated by Django 5.0.3 on 2024-03-30 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=4000)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.IntegerField(default=0)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterForEvent',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_sender_phone', models.IntegerField(default=0)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registerforevent')),
            ],
        ),
    ]
